# Prettier configuration
overrides:
  - files:
      - "*.java"
    options:
      printWidth: 110
      tabWidth: 4
      useTabs: false
      trailingComma: none

      #npx prettier --write "/*.java". prettier --write "/*.java".
